### ISSUE TITLE
Can I have additional urls?

### ISSUE THREAD

**Issue by Mpreyzner** [rezzza/rest-api-behat-extension#82]
For my tests I need to have 2 additional urls (beside base_url). Is it possible to use more than one url?

**Comment by tyx** [comment]
Hello,

unfortunately it is not possible because it would be a real mess to handle. 

But there is a workaround :sunglasses: ! 
Indeed, the `RestApiBrowser` will prepend the `base_url` only if you ask for a path query (like `/designs`). With complete url (like ` http://my.api.local/designs`), no problem, it will use this url.

```php
// Will request http://base_url/designs
$this->restApiBrowser->sendRequest('GET', '/designs');

// Will request http://my.api.local/designs even if base_url is defined
$this->restApiBrowser->sendRequest('GET', 'http://my.api.local/designs');
``` 
Hope it helps
